# Generated by Django 3.1.1 on 2020-11-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_testdg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
