# Generated by Django 3.1.1 on 2020-11-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201108_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvps',
            field=models.IntegerField(default=0),
        ),
    ]
