# Generated by Django 3.1.1 on 2020-11-13 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_rsvps'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='people_going',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=[], size=None),
        ),
    ]
